### ISSUE TITLE
How can we make this work for methods called from other methods?

### ISSUE THREAD

**Issue by monsterxxx** [themeteorchef/server-only-methods#4]
For example, I want to Meteor.call('createUser') from another method, but don't want to let client call it straight from browser. In this case this.connection on server is not null. Thank you!

P.S.
Currently I'm using function createUser declared in server/users.js without var keyword.

**Comment by DylanKojiCheslin** [comment]
+1

**Comment by avalanche1** [comment]
Seems like storing your code in a fucntion instead of method is the only option.

**Comment by themeteorchef** [comment]
Sorry for not responding! @avalanche1 is correct here.

**Comment by monsterxxx** [comment]
Yeah thx, function way is quite tolerable)
